[package]
name = "callsign"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "Apache-2.0"

[lib]
name = "callsign"
path = "src/callsign.rs"

[dependencies]
rusqlite = { version = "0.37.0", features = ["bundled"] }
r2d2 = "0.8.10"
r2d2_sqlite = "0.31.0"